services:
  backend:
    image: europe-southwest1-docker.pkg.dev/qdsp-389210/cloud-run-source-deploy/qdsp-backend/qdsp:a3240c060ca01d3812f50ea5a17c1377bb626e4a
    ports:
      - "4000:4000"
    env_file:
      - backend.env
    environment:
      SECRET_KEY_BASE: "secret"
