services:
  backend:
    image: europe-southwest1-docker.pkg.dev/qdsp-389210/cloud-run-source-deploy/qdsp-backend/qdsp:latest
    ports:
      - "4000:4000"
    env_file:
      - backend.env
    environment:
      SECRET_KEY_BASE: "secret"
      REDIS_HOST: "redis"

  redis:
    image: redis
